Vmp 117 differ scooters by group range
VooomPL/OpenTripPlanner pull request #118
Opened 2020-10-20 09:42 UTC by MironSz

2020-10-20 10:49 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +        numberOfKickScooterGroups = kickscooterRangeGroupsInMeters.size();
Tutaj powinno być ` + 1`.

2020-10-20 10:49 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +        this.kickscooterRangeGroupsInMeters = kickscooterRangeGroupsInMeters;
Powinieneś robić nową listę `ArrayList`, bo nie masz pewności, że będziesz się mógł szybko poruszać po niej indeksami.

2020-10-20 10:52 UTC, AdamWiktor requested changes
Zmerguj to dopiero jak wprowadzisz zmiany z endpointem do benchmarków - bo tutaj są zmiany z obu PRów

2020-10-20 10:52 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +public class RoutingStateDiffOptions implements Serializable {
Może jakiś teścik?

2020-10-23 07:35 UTC, MironSz commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +        numberOfKickScooterGroups = kickscooterRangeGroupsInMeters.size();
Done z zmianami dodatkowymi niestety

2020-10-23 07:35 UTC, MironSz commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +        this.kickscooterRangeGroupsInMeters = kickscooterRangeGroupsInMeters;
Sure, zrobione

2020-10-23 07:36 UTC, MironSz commented on src/main/java/org/opentripplanner/routing/core/routing_parametrizations/RoutingStateDiffOptions.java
> +public class RoutingStateDiffOptions implements Serializable {
Dodałem quality testy (tak mi się wydają przynajmniej :D) które wykryły drobne błędy

2020-10-23 09:06 UTC, AdamWiktor approved these changes

2020-10-23 10:22 UTC, Kamyki approved these changes

2020-10-23 14:53 UTC, merged