Vmp 70 veturillo stations
VooomPL/OpenTripPlanner pull request #88
Opened 2020-09-01 08:53 UTC by MironSz

Dodałem rowery wypożyczane i oddawane na stacjach. Rowery są widoczne dopiero jak OTP zaczyta i przetworzy strefy parkowania. Przykładowe zapytanie które znajduje trasę rowerem

http://localhost:8080/otp/routers/default/plan?fromPlace=52.296298,20.9583575&toPlace=52.2909738,20.9295559&mode=WALK,BICYCLE&rentingAllowed=true

2020-09-03 12:39 UTC, AdamWiktor requested changes
chciałbym jeszcze przegadać to updatowanie stref parkowania - wydaje mi się, że nie jest potrzebne i że da się to zrobić łatwiej

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/hasura_client/hasura_objects/BikeStationHasura.java
> +    private int spacesAvaiable;
Tu i linijkę wyżej: `available`

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStation.java
> +    public double longitude, latitude; //longitude, latitude
został zbędny komentarz

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/KickScooterOrBikeDescription.java
> +
formatowanie (podwójne nowe linie, brak nowej linii przed TRAVERSE_MODE)

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/KickScooterOrBikeDescription.java
> +public abstract class KickScooterOrBikeDescription extends VehicleDescription {
`BikePathVehicleDescription`

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/BikeDescription.java
> +    private static final double DEFAULT_RANGE_IN_METERS = 16 * 1000;
technicznie to rower nie ma maksymalnego zasięgu xD. Z drugiej strony nie chcemy, żeby planner sugerował trasy między miastami rowerem, także nie wiem co tu powinno być

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/VehicleDescription.java
> +    protected boolean hubbable;
`protected boolean requiresHubToDropoff`

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/ParkingZoneInfo.java
> +        if (vehicle.isHubbable())
niech to będzie oddzielne sprawdzenie w oddzielnej funkcji o długiej nazwie

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/VehicleType.java
> +    BIKE;
`BIKE` czy `BICYCLE`? otwarta dyskusja, bo sam nie wiem

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/RentVehicleEdge.java
> +    private BikeRentalStation bikeRentalStation = null;
może oddzielna klasa `RentBikeEdge` ? To jest spory hack, że mamy `vehicle` oraz `bikeRentalStation` i zawsze tylko jedno nie jest nullem

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/graph/Graph.java
> +        return getEdges().stream().filter(e -> e instanceof DropoffVehicleEdge).map(e -> (DropoffVehicleEdge) e);
do `instanceof` i castowania polecam `.filter(DropoffVehicleEdge.class:isInstance).map(DropoffVehicleEdge.class::cast)`

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/graph/Graph.java
> +        return getEdges().stream().filter(e -> e instanceof DropoffVehicleEdge).map(e -> (DropoffVehicleEdge) e);
ale to raczej kwestia stylistyczna, jak kto woli

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/updater/vehicle_sharing/vehicles_positions/BikesUpdater.java
> +//TODO one huge todo for miron
what

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/updater/vehicle_sharing/vehicles_positions/BikeStationsGraphWriterRunnable.java
> +    public final TemporaryStreetSplitter temporaryStreetSplitter;
private

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/graph/Graph.java
> +        this.bikeRentalStationsInGraph = new ConcurrentHashMap<>();
to nie musi być concurrent, bo używasz tego tylko przez jeden scheduler w danym momencie. Możesz zrobić `public Map<BikeRentalStation, RentVehicleEdge> bikeRentalStationsInGraph = new HashMap<>();`

2020-09-03 12:39 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/updater/vehicle_sharing/vehicles_positions/BikeStationsGraphWriterRunnable.java
> +        return true;
;_;

2020-09-03 13:38 UTC, MironSz commented on src/main/java/org/opentripplanner/routing/graph/Graph.java
> +        return getEdges().stream().filter(e -> e instanceof DropoffVehicleEdge).map(e -> (DropoffVehicleEdge) e);
Dzięki, brakowało mi tego

2020-09-03 18:27 UTC, MironSz commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/VehicleType.java
> +    BIKE;
Chyba oba, bike jest krótsze a równie ekspresywne

2020-09-04 09:44 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/DropBikeEdge.java
> +    private BikeRentalStation station;
final

2020-09-04 09:45 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/RentBikeEdge.java
> +    final private BikeRentalStation station;
private

2020-09-04 09:48 UTC, AdamWiktor approved these changes

2020-09-04 09:50 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/graph_builder/linking/TemporaryStreetSplitter.java
> +    private TemporaryRentVehicleVertex createTemporaryRentVehicleVertex(BikeRentalStation station) {
RentBike

2020-09-04 09:54 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/core/vehicle_sharing/BikePathVehicleDescription.java
> +public abstract class BikePathVehicleDescription extends VehicleDescription {
może jakiś komentarz, że to są pojazdy, które mogą trasować się po chodniku i ścieżkach rowerowych

2020-09-04 09:55 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/DropBikeEdge.java
> +public class DropBikeEdge extends DropoffVehicleEdge {
może komentarz, że to jest tylko do oddawania rowerów i jest tylko w wierzchołkach przy stacjach rowerowych

2020-09-04 09:56 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/DropBikeEdge.java
> +    public DropBikeEdge(Vertex v, BikeRentalStation station) {
`TemporaryRentVehicleVertex v`

2020-09-04 09:58 UTC, AdamWiktor commented on src/main/java/org/opentripplanner/routing/edgetype/rentedgetype/RentBikeEdge.java
> +public class RentBikeEdge extends RentVehicleEdge {
komentarz, że to jest krawędź do wypożyczania rowerów albo do zamiany dowolnego INNEGO pojazdu na rower (to jest dość istotne, bo teraz ta logika jest taka, że w tej krawędzi możemy tylko wziąć rower, albo zamienić np hulajnogę na rower, a w krawędzi do zwracania (która jest w tym samym wierzchołku) możemy oddać tylko rower).

2020-09-07 06:04 UTC, merged